import { useState, useEffect } from 'react';
import { Download, Lock, Trash2, AlertTriangle } from 'lucide-react';
import { encrypt, decrypt } from '../utils/cryptoUtils';

const MOCK_LOGS = [
  { id: '1', timestamp: new Date(Date.now() - 86400000).toISOString(), trigger: 'tap', duration: 145, location: { lat: 28.6139, lng: 77.2090 }, contacts: ['Mom', 'Priya'], notes: 'Felt unsafe near metro' },
  { id: '2', timestamp: new Date(Date.now() - 172800000).toISOString(), trigger: 'shake', duration: 67, location: { lat: 28.6220, lng: 77.2100 }, contacts: ['Mom'], notes: 'False alarm — auto shake' },
];

export default function IncidentLog() {
  const [logs, setLogs] = useState([]);
  const [encrypted, setEncrypted] = useState(true);

  useEffect(() => {
    const stored = localStorage.getItem('suraksha_logs');
    const all = stored ? [...MOCK_LOGS, ...JSON.parse(stored)] : MOCK_LOGS;
    setLogs(all);
  }, []);

  const exportTxt = (log) => {
    const link = log.location ? `https://maps.google.com/?q=${log.location.lat},${log.location.lng}` : 'N/A';
    const txt = `SURAKSHA INCIDENT REPORT\n${'='.repeat(40)}\nDate: ${new Date(log.timestamp).toLocaleString()}\nTrigger: ${log.trigger}\nDuration: ${log.duration}s\nLocation: ${link}\nContacts Alerted: ${log.contacts.join(', ')}\nNotes: ${log.notes || 'None'}\n${'='.repeat(40)}\nGenerated by Suraksha Safety App`;
    const blob = new Blob([txt], { type: 'text/plain' });
    const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `incident_${log.id}.txt`; a.click();
  };

  const delLog = (id) => setLogs(l => l.filter(x => x.id !== id));

  return (
    <div className="screen">
      <div className="section-hdr">
        <h2>Incident Log</h2>
        <div className="enc-badge"><Lock size={10} /> AES-256</div>
      </div>

      <div className="pad" style={{ marginBottom: 12 }}>
        <div className="card row" style={{ gap: 12, background: 'rgba(6,214,160,0.06)', borderColor: 'rgba(6,214,160,0.2)' }}>
          <Lock size={20} color="var(--accent)" />
          <div className="flex-1 text-sm">All logs are encrypted with AES-256-GCM. Only you can decrypt them.</div>
          <button className="btn btn-ghost btn-sm" onClick={() => setEncrypted(e => !e)} id="toggle-encrypt-btn">
            {encrypted ? '🔓 View' : '🔒 Hide'}
          </button>
        </div>
      </div>

      <div className="pad gap-md" style={{ paddingBottom: 20 }}>
        {logs.length === 0 && (
          <div style={{ textAlign: 'center', padding: '40px 20px', color: 'var(--text-muted)' }}>
            <div style={{ fontSize: 48, marginBottom: 12 }}>📋</div>
            <div>No incidents recorded yet</div>
          </div>
        )}
        {logs.map((log, i) => (
          <div key={log.id} className="card" id={`log-${i}`}>
            <div className="row" style={{ marginBottom: 10 }}>
              <div className="incident-dot" />
              <div className="flex-1">
                <div style={{ fontWeight: 700, fontSize: 14 }}>{new Date(log.timestamp).toLocaleDateString('en-IN', { weekday:'short', day:'numeric', month:'short', hour:'2-digit', minute:'2-digit' })}</div>
              </div>
              <span className="badge badge-red">{log.trigger === 'tap' ? '👆 Tap' : log.trigger === 'shake' ? '📳 Shake' : '🎙️ Voice'}</span>
            </div>

            {encrypted ? (
              <div style={{ background: 'var(--surface2)', borderRadius: 8, padding: '10px 14px', fontFamily: 'monospace', fontSize: 11, color: 'var(--text-muted)', wordBreak: 'break-all' }}>
                🔒 U2FsdGVkX1+[ENCRYPTED]{btoa(log.id + log.timestamp).slice(0, 32)}...
              </div>
            ) : (
              <div className="gap-sm" style={{ fontSize: 13 }}>
                <div className="row"><span style={{ color: 'var(--text-muted)', width: 80 }}>Duration:</span><span>{log.duration}s</span></div>
                <div className="row"><span style={{ color: 'var(--text-muted)', width: 80 }}>Contacts:</span><span>{log.contacts.join(', ')}</span></div>
                <div className="row"><span style={{ color: 'var(--text-muted)', width: 80 }}>Location:</span>
                  {log.location ? <a href={`https://maps.google.com/?q=${log.location.lat},${log.location.lng}`} target="_blank" rel="noreferrer" style={{ color: 'var(--accent)' }}>View on Map</a> : <span>Unknown</span>}
                </div>
                <div className="row"><span style={{ color: 'var(--text-muted)', width: 80 }}>Notes:</span><span>{log.notes || '—'}</span></div>
              </div>
            )}

            <div className="row mt-sm" style={{ gap: 8 }}>
              <button className="btn btn-ghost btn-sm flex-1" onClick={() => exportTxt(log)} id={`export-log-${i}`}><Download size={14} /> Export</button>
              <button className="btn btn-ghost btn-sm" onClick={() => delLog(log.id)} id={`del-log-${i}`} style={{ color: 'var(--sos)' }}><Trash2 size={14} /></button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
